### ISSUE TITLE
Where does the component go?

### ISSUE THREAD

**Issue by tfcarlin** [screek-workshop/screek_light_sensor#1] opened 2023-06-11 22:48 UTC
Where should screek-components/esp32 go on Home Assistant?

**Comment by tfcarlin** [comment] 2023-06-11 23:00
It would be nice if you had a simple example like this:

https://github.com/tiaanv/esphome-components

**Comment by tfcarlin** [comment] 2023-06-11 23:55
I got this to work by creating a personal copy of the repository. Doesn't seem like a good idea. I upload the .bin file but it doesn't appear to be working.

Here is the yaml file used by ESPHome

```
esphome:
  name: luxsensor-mbr
  comment: Screek Light-Sensor 1A MBR
  friendly_name: LuxSensor-MBR
  name_add_mac_suffix: True
  platformio_options:
    board_build.flash_mode: dio
  project: 
    name: Screek.Light_Sensor
    version: 1A

esp32:
  board: lolin_c3_mini
  framework:
    type: arduino
    version: 2.0.7
    platform_version: 6.0.1

external_components:
  - source: github://tfcarlin/screek-light-sensor
    components: ["esp32"]

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

wifi:
  ssid: xxxx
  password: xxx

captive_portal:

improv_serial:
  

i2c:
  sda: GPIO7
  scl: GPIO11
  scan: true
  id: bus_a

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected

sensor:
  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 30s
    entity_category: "diagnostic"
  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 10s
  - platform: wifi_signal 
    name: RSSI
    id: wifi_signal_db
    update_interval: 5s
    entity_category: "diagnostic"
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"
    disabled_by_default: True
  - platform: bh1750
    name: "Illuminance"
    # address: 0x23
    update_interval: 1s

light:
  - platform: status_led
    name: sys_status
    pin: GPIO12
    internal: True
    restore_mode: ALWAYS_OFF
  - platform: status_led
    name: sys_status
    pin: GPIO13
    internal: True
    restore_mode: ALWAYS_OFF

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
  - platform: factory_reset
    disabled_by_default: True
    name: Factory Reset
    id: factory_reset_all
```

**Comment by screek-workshop** [comment] 2023-06-12 00:20
> 
hi there:)

I'm afraid ota won't work, this is because of the protection of the ota password, we don't provide the ota password here because it prevents someone from maliciously using it to rewrite another running firmware.  
Here there will be a problem involved, you need to prepare an ota password, and at the same time, you need to initialize the homebrew by plugging it into your computer and burning it with usb.  
After that, you can update the ota firmware with your own ota password. 

There is a seemingly strange bug with esphome's ota, it shows SUCCESS as soon as the firmware is uploaded, but that doesn't mean the new firmware is applied.

**Comment by screek-workshop** [comment] 2023-06-12 00:24
> Where should screek-components/esp32 go on Home Assistant?

you can just drag it to the config folder, as a subfolder.
We don't want to put it in the public library because, it's actually a hack, esp32 is a built-in library and we made changes to it, and this is so that we can use the two SPI vdd pins of ESP32-C3, otherwise we would have no indicator.  
But as the esphome is constantly upgraded, the esp32 library will be constantly changed.  
So, I'm afraid there is no one suitable for all esphome versions esp32.

**Comment by tfcarlin** [comment] 2023-06-12 00:32
> > 
> 
> hi there:)
> 
> I'm afraid ota won't work, this is because of the protection of the ota password, we don't provide the ota password here because it prevents someone from maliciously using it to rewrite another running firmware. Here there will be a problem involved, you need to prepare an ota password, and at the same time, you need to initialize the homebrew by plugging it into your computer and burning it with usb. After that, you can update the ota firmware with your own ota password.
> 
> There is a seemingly strange bug with esphome's ota, it shows SUCCESS as soon as the firmware is uploaded, but that doesn't mean the new firmware is applied.
> 
> and esp web tool, we do the tricky too:
> 
> > https://www.youtube.com/watch?v=-dOTuEubObU

Thanks. I used this https://web.esphome.io/?dashboard_install without any issues.

**Comment by screek-workshop** [comment] 2023-06-12 00:33
i update some note in the yaml.
thank you feedback.  

you can close the issue, if is work.

**Comment by tfcarlin** [comment] 2023-06-12 00:34
> > Where should screek-components/esp32 go on Home Assistant?
> 
> you can just drag it to the config folder, as a subfolder. We don't want to put it in the public library because, it's actually a hack, esp32 is a built-in library and we made changes to it, and this is so that we can use the two SPI vdd pins of ESP32-C3, otherwise we would have no indicator. But as the esphome is constantly upgraded, the esp32 library will be constantly changed. So, I'm afraid there is no one suitable for all esphome versions esp32.

Hum...I tried this but couldn't get it to work. Maybe post a screenshot of the exact file structure. I was attempting to do this using Studio Coder Server in HA. Is there a better way? Thanks!

**Comment by screek-workshop** [comment] 2023-06-12 00:41
> > > Where should screek-components/esp32 go on Home Assistant?
> > 
> > 
> > you can just drag it to the config folder, as a subfolder. We don't want to put it in the public library because, it's actually a hack, esp32 is a built-in library and we made changes to it, and this is so that we can use the two SPI vdd pins of ESP32-C3, otherwise we would have no indicator. But as the esphome is constantly upgraded, the esp32 library will be constantly changed. So, I'm afraid there is no one suitable for all esphome versions esp32.
> 
> Hum...I tried this but couldn't get it to work. Maybe post a screenshot of the exact file structure. I was attempting to do this using Studio Coder Server in HA. Is there a better way? Thanks!

i install the esphome in my main machine, use the python-env, which much faster compile time, here is how i put the folder:

![image](https://github.com/screek-workshop/screek_light_sensor/assets/126383355/74eb1343-8546-4273-825c-319a568c31c9)

**Comment by screek-workshop** [comment] 2023-06-12 00:43
The format I use is something like this:

```yaml
external_components:
  - source: screek-components
```

the document is here: 
https://esphome.io/components/external_components.html#external-components
https://esphome.io/components/external_components.html#local

**Comment by screek-workshop** [comment] 2023-06-12 00:44
this way should be work too.

```bash
external_components:
  - source:
      type: local
      path: screek-components
```

**Comment by screek-workshop** [comment] 2023-06-12 00:46
> > > Where should screek-components/esp32 go on Home Assistant?
> > 
> > 
> > you can just drag it to the config folder, as a subfolder. We don't want to put it in the public library because, it's actually a hack, esp32 is a built-in library and we made changes to it, and this is so that we can use the two SPI vdd pins of ESP32-C3, otherwise we would have no indicator. But as the esphome is constantly upgraded, the esp32 library will be constantly changed. So, I'm afraid there is no one suitable for all esphome versions esp32.
> 
> Hum...I tried this but couldn't get it to work. Maybe post a screenshot of the exact file structure. I was attempting to do this using Studio Coder Server in HA. Is there a better way? Thanks!
> 
> Here is what I tried:
> 
> ![image](https://user-images.githubusercontent.com/115871/244982887-46fed908-0794-4e4b-be1e-2925fbad11db.png) or ![image](https://user-images.githubusercontent.com/115871/244982992-7957f419-6790-4c57-b74b-8165bf67cf3a.png)
> 
> And the result:
> 
> ![image](https://user-images.githubusercontent.com/115871/244982832-45710ae9-5b8a-4de8-8a2e-a0f1f33f14ff.png)

i think the problem is you should put it in esphome folder:)
which you are install in the server.

the config folder is esphome folder, not the homeassistant folder.

so the error is mean it cant location the folder.

**Comment by tfcarlin** [comment] 2023-06-12 00:48
> > > > Where should screek-components/esp32 go on Home Assistant?
> > > 
> > > 
> > > you can just drag it to the config folder, as a subfolder. We don't want to put it in the public library because, it's actually a hack, esp32 is a built-in library and we made changes to it, and this is so that we can use the two SPI vdd pins of ESP32-C3, otherwise we would have no indicator. But as the esphome is constantly upgraded, the esp32 library will be constantly changed. So, I'm afraid there is no one suitable for all esphome versions esp32.
> > 
> > 
> > Hum...I tried this but couldn't get it to work. Maybe post a screenshot of the exact file structure. I was attempting to do this using Studio Coder Server in HA. Is there a better way? Thanks!
> > Here is what I tried:
> > ![image](https://user-images.githubusercontent.com/115871/244982887-46fed908-0794-4e4b-be1e-2925fbad11db.png) or ![image](https://user-images.githubusercontent.com/115871/244982992-7957f419-6790-4c57-b74b-8165bf67cf3a.png)
> > And the result:
> > ![image](https://user-images.githubusercontent.com/115871/244982832-45710ae9-5b8a-4de8-8a2e-a0f1f33f14ff.png)
> 
> i think the problem is you should put it in esphome folder:) which you are install in the server.
> 
> the config folder is esphome folder, not the homeassistant folder.
> 
> so the error is mean it cant location the folder.

That fixed the issue. Thanks!

**Comment by screek-workshop** [comment] 2023-06-12 00:49
i so sorry make you confuse, i change thenote by: 
> place the subfolder screek-components from the source directory into the esphome yaml file root directory

nice day:)

**Closed** 2023-06-12 00:49 UTC
